In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("D:\Data_Sets\diabetes.csv")

In [3]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [10]:
X=dataset.iloc[:,[0,1,2,3,4,6,7]].values
y=dataset.iloc[:,5].values

In [11]:
X

array([[  6.   , 148.   ,  72.   , ...,   0.   ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.   ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,   0.   ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ..., 112.   ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,   0.   ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.   ,   0.315,  23.   ]])

In [12]:
y

array([33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31. , 35.3, 30.5,  0. , 37.6,
       38. , 27.1, 30.1, 25.8, 30. , 45.8, 29.6, 43.3, 34.6, 39.3, 35.4,
       39.8, 29. , 36.6, 31.1, 39.4, 23.2, 22.2, 34.1, 36. , 31.6, 24.8,
       19.9, 27.6, 24. , 33.2, 32.9, 38.2, 37.1, 34. , 40.2, 22.7, 45.4,
       27.4, 42. , 29.7, 28. , 39.1,  0. , 19.4, 24.2, 24.4, 33.7, 34.7,
       23. , 37.7, 46.8, 40.5, 41.5,  0. , 32.9, 25. , 25.4, 32.8, 29. ,
       32.5, 42.7, 19.6, 28.9, 32.9, 28.6, 43.4, 35.1, 32. , 24.7, 32.6,
       37.7, 43.2, 25. , 22.4,  0. , 29.3, 24.6, 48.8, 32.4, 36.6, 38.5,
       37.1, 26.5, 19.1, 32. , 46.7, 23.8, 24.7, 33.9, 31.6, 20.4, 28.7,
       49.7, 39. , 26.1, 22.5, 26.6, 39.6, 28.7, 22.4, 29.5, 34.3, 37.4,
       33.3, 34. , 31.2, 34. , 30.5, 31.2, 34. , 33.7, 28.2, 23.2, 53.2,
       34.2, 33.6, 26.8, 33.3, 55. , 42.9, 33.3, 34.5, 27.9, 29.7, 33.3,
       34.5, 38.3, 21.1, 33.8, 30.8, 28.7, 31.2, 36.9, 21.1, 39.5, 32.5,
       32.4, 32.8,  0. , 32.8, 30.5, 33.7, 27.3, 37

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.87, random_state=500)

In [90]:
X_train

array([[0.000e+00, 1.620e+02, 7.600e+01, 3.600e+01, 0.000e+00, 3.640e-01,
        2.600e+01],
       [6.000e+00, 1.150e+02, 6.000e+01, 3.900e+01, 0.000e+00, 2.450e-01,
        4.000e+01],
       [1.000e+00, 1.130e+02, 6.400e+01, 3.500e+01, 0.000e+00, 5.430e-01,
        2.100e+01],
       [1.000e+01, 9.000e+01, 8.500e+01, 3.200e+01, 0.000e+00, 8.250e-01,
        5.600e+01],
       [4.000e+00, 1.460e+02, 7.800e+01, 0.000e+00, 0.000e+00, 5.200e-01,
        6.700e+01],
       [3.000e+00, 1.250e+02, 5.800e+01, 0.000e+00, 0.000e+00, 1.510e-01,
        2.400e+01],
       [3.000e+00, 1.020e+02, 7.400e+01, 0.000e+00, 0.000e+00, 1.210e-01,
        3.200e+01],
       [0.000e+00, 1.130e+02, 8.000e+01, 1.600e+01, 0.000e+00, 8.740e-01,
        2.100e+01],
       [4.000e+00, 1.560e+02, 7.500e+01, 0.000e+00, 0.000e+00, 2.380e-01,
        3.200e+01],
       [2.000e+00, 1.090e+02, 9.200e+01, 0.000e+00, 0.000e+00, 8.450e-01,
        5.400e+01],
       [4.000e+00, 1.510e+02, 9.000e+01, 3.800e+01, 0.000e+0

In [91]:
X_test

array([[3.00e+00, 1.70e+02, 6.40e+01, ..., 2.25e+02, 3.56e-01, 3.00e+01],
       [5.00e+00, 1.04e+02, 7.40e+01, ..., 0.00e+00, 1.53e-01, 4.80e+01],
       [9.00e+00, 1.40e+02, 9.40e+01, ..., 0.00e+00, 7.34e-01, 4.50e+01],
       ...,
       [9.00e+00, 1.70e+02, 7.40e+01, ..., 0.00e+00, 4.03e-01, 4.30e+01],
       [2.00e+00, 8.40e+01, 5.00e+01, ..., 7.60e+01, 9.68e-01, 2.10e+01],
       [0.00e+00, 1.24e+02, 5.60e+01, ..., 1.05e+02, 4.52e-01, 2.10e+01]])

In [92]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [93]:
X_test

array([[3.00e+00, 1.70e+02, 6.40e+01, ..., 2.25e+02, 3.56e-01, 3.00e+01],
       [5.00e+00, 1.04e+02, 7.40e+01, ..., 0.00e+00, 1.53e-01, 4.80e+01],
       [9.00e+00, 1.40e+02, 9.40e+01, ..., 0.00e+00, 7.34e-01, 4.50e+01],
       ...,
       [9.00e+00, 1.70e+02, 7.40e+01, ..., 0.00e+00, 4.03e-01, 4.30e+01],
       [2.00e+00, 8.40e+01, 5.00e+01, ..., 7.60e+01, 9.68e-01, 2.10e+01],
       [0.00e+00, 1.24e+02, 5.60e+01, ..., 1.05e+02, 4.52e-01, 2.10e+01]])

In [94]:
y_test

array([34.5, 28.8, 32.7, 40.9, 27.7, 39.1, 31.2, 43.6, 40.6, 24. , 40.5,
       27.8, 31.3, 46.7, 30.5, 37.2, 30.9, 32.8, 39.4, 32. , 35.8, 35.1,
       36.9, 25.3, 21. , 40.5, 26.6, 45.3, 44. , 20.1, 21.8, 32. , 45. ,
       33.2, 33.2, 29.7, 28.6, 36.3, 30.4, 23.4, 40. , 26.4, 38.5, 22.5,
       26.6, 46.2, 31.2, 30.8, 32.8, 43.3, 30.5, 46.8, 37.7, 43.5, 27.6,
       45.5,  0. , 35.3, 37.6, 39.2, 21.2, 28. , 35.7, 28.7, 38.6, 28. ,
       36.6, 39.4, 30.8, 38.7, 33.6, 44.2, 26.2, 25.1, 29.5, 38.7, 25.9,
       34. , 36.1, 27.3, 23.5, 25.9, 34.2, 34. , 31.2, 25.4, 28.2, 36.4,
       33.9, 25.4, 30.7, 25.8, 37.7,  0. , 42.9, 24.2, 21.8, 44.1, 36.1,
       52.9, 25.9, 35.8, 34.6, 52.3, 34.9, 22.4, 35.1, 24.6, 23. , 29.5,
       20.4, 21.1, 36.9, 23.2, 39.9, 45.3, 37.4, 38.1, 26.6, 22.9, 24.3,
       59.4, 32.9, 25.6, 33.3, 34.3, 42.4, 32.8, 35.2, 29.7, 26.2, 29.7,
       20.8, 29. , 43.2, 30.8, 35.4, 22.4, 23.6, 22.1, 30.8, 53.2, 30.1,
       46.1, 35.1, 30. , 35.8, 24. , 31.6, 39. , 24

In [95]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [98]:
y_pred=regressor.predict([[1,93,70,31,0,0.315,23]])

print(y_pred)

[34.30653549]
