In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("D:\Data_Sets\Brain Stroke.csv")

In [3]:
dataset

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [4]:
dataset.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [5]:
X=dataset.iloc[:,[1,7]].values
y=dataset.iloc[:,-3].values

In [6]:
X

array([[ 67.  , 228.69],
       [ 80.  , 105.92],
       [ 49.  , 171.23],
       ...,
       [ 45.  ,  95.02],
       [ 40.  ,  83.94],
       [ 80.  ,  83.75]])

In [7]:
y

array([36.6, 32.5, 34.4, ..., 31.8, 30. , 29.1])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =20)

In [9]:
X_train

array([[ 68.  ,  96.75],
       [  0.48, 118.75],
       [ 25.  ,  93.88],
       ...,
       [ 65.  ,  58.87],
       [  8.  ,  63.43],
       [ 15.  ,  77.55]])

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [11]:
X_test

array([[ 53.  ,  73.6 ],
       [ 82.  ,  59.32],
       [ 56.  ,  72.79],
       ...,
       [ 21.  , 111.61],
       [ 33.  ,  99.3 ],
       [  6.  , 123.39]])

In [12]:
y_test

array([27. , 33.2, 23.8, ..., 36.9, 21.4, 15.2])

In [13]:
y_pred = regressor.predict([[15.  ,  77.55]])

print(y_pred)

[25.22446876]
